name: Notify

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notify:
    name: Submodule Notify Parent
    runs-on: ubuntu-latest

    steps:
    - name: Workflow dispatch event
      env:
        PARENT_REPO: ${{ secrets.PARENT_REPO }}
        PARENT_ID: ${{ secrets.PARENT_ID }}
      run: |
        data="{\"ref\":\"${GITHUB_REF_NAME}\"}"
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          $GITHUB_API_URL/repos/$PARENT_REPO/actions/workflows/$PARENT_ID/dispatches \
          -d "$data"
